### ISSUE TITLE
missing <filesystem>

### ISSUE THREAD

**Issue by aaronthor** [google/fully-homomorphic-encryption#11]
Hi, have been trying to run several provided examples (pls see attached) but keeps having failures. 
using --verbose_failures and --sandbox_debug reveals that:
"external/com_google_xls/xls/passes/pass_base.h:20:10: fatal error: filesystem: No such file or directory"
Kindly advise. Much appreciated.
NB: am running ubuntu 18.04 VM with bazel 4.0.0 as instructed at: https://github.com/google/fully-homomorphic-encryption/tree/main/transpiler

Thank you
[failure.log](https://github.com/google/fully-homomorphic-encryption/files/6711421/failure.log)

**Comment by dibakch** [comment]
Can you check `gcc --version` to verify that you installed gcc in at least version 9?

**Comment by aaronthor** [comment]
> Can you check `gcc --version` to verify that you installed gcc in at least version 9?

Thank you for looking into this! Duh! The page clearly stated dependency on gcc-9. Too used to ubuntu 20.04 - I just had the assumption that ubuntu18.04 comes with gcc-9 by default.. Good catch as it came with gcc7.5.0. My bad. Have upgraded to gcc-9 and performed the softlink updates for gcc (and g++). Re-ran and it had some dependencies issues - probably due to the previously compiled remninants. Have flushed everything in the .cache directory and performed a fresh re-run of the examples at with success. Much appreciate your help Christoph! 
BTW, just wanted to say great work on this! Been playing with Google's PJC but this is way ahead with the use of XLS. Will be following this project closely. Keep up the great work! 

Cheers,
Aaron
