### ISSUE TITLE
Compile erro on the reverse string example

### ISSUE THREAD

**Issue by ahdach** [google/fully-homomorphic-encryption#17]
Hi,

First, I want to thank you for this project. Its really nice and has enormous potential.

I'm compiling from the sources on a EC2 machine.
I had an error when I was at the examples compilation. The reverse string example. You will find the error messages hereafter. How can I fix this?

The simple sum example still worked. So I can continue my exploration.

Thanks in advance for your help.

Kind Regards,
M

---

ERROR: /home/ec2-user/fully-homomorphic-encryption/transpiler/examples/string_reverse/BUILD:21:15: Compiling transpiler/examples/string_reverse/string_reverse_tfhe.cc failed: (Exit 4): linux-sandbox failed: error executing command
  (cd /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption && \
  exec env - \
    BAZEL_CXXOPTS='-std=c++17' \
    LD_LIBRARY_PATH=/home/ec2-user/opt/gcc-9.1.0/lib:/home/ec2-user/opt/gcc-9.1.0/lib64:/home/ec2-user/opt/gcc-9.1.0/lib:/home/ec2-user/opt/gcc-9.1.0/lib64: \
    PATH=/home/ec2-user/.cache/bazelisk/downloads/bazelbuild/bazel-4.0.0-linux-x86_64/bin:/home/ec2-user/opt/gcc-9.1.0/bin:/home/ec2-user/opt/gcc-9.1.0/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    TMPDIR=/tmp \
  /home/ec2-user/.cache/bazel/_bazel_ec2-user/install/1a4a2fac02d50c77031d44c0d91b8920/linux-sandbox -t 15 -w /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption -w /tmp -w /dev/shm -D -- /home/ec2-user/opt/gcc-9.1.0/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++17' -MD -MF bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.d '-frandom-seed=bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -isystem bazel-out/k8-opt/bin/external/tfhe/libtfhe/include -Wno-sign-compare -Wno-comment '-std=c++17' -O0 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/k8-opt/bin/transpiler/examples/string_reverse/string_reverse_tfhe.cc -o bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.o) linux-sandbox failed: error executing command
  (cd /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption && \
  exec env - \
    BAZEL_CXXOPTS='-std=c++17' \
    LD_LIBRARY_PATH=/home/ec2-user/opt/gcc-9.1.0/lib:/home/ec2-user/opt/gcc-9.1.0/lib64:/home/ec2-user/opt/gcc-9.1.0/lib:/home/ec2-user/opt/gcc-9.1.0/lib64: \
    PATH=/home/ec2-user/.cache/bazelisk/downloads/bazelbuild/bazel-4.0.0-linux-x86_64/bin:/home/ec2-user/opt/gcc-9.1.0/bin:/home/ec2-user/opt/gcc-9.1.0/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    TMPDIR=/tmp \
  /home/ec2-user/.cache/bazel/_bazel_ec2-user/install/1a4a2fac02d50c77031d44c0d91b8920/linux-sandbox -t 15 -w /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption -w /tmp -w /dev/shm -D -- /home/ec2-user/opt/gcc-9.1.0/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++17' -MD -MF bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.d '-frandom-seed=bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -isystem bazel-out/k8-opt/bin/external/tfhe/libtfhe/include -Wno-sign-compare -Wno-comment '-std=c++17' -O0 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/k8-opt/bin/transpiler/examples/string_reverse/string_reverse_tfhe.cc -o bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.o)
1633081675.458286222: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1633081675.458319820: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1633081675.458528898: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 13104
1633081675.458580542: src/main/tools/linux-sandbox-pid1.cc:434: Pid1Main started
1633081675.458663780: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1633081675.458809255: src/main/tools/linux-sandbox-pid1.cc:176: working dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption
1633081675.458824961: src/main/tools/linux-sandbox-pid1.cc:208: writable: /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption
1633081675.458832192: src/main/tools/linux-sandbox-pid1.cc:208: writable: /tmp
1633081675.458839008: src/main/tools/linux-sandbox-pid1.cc:208: writable: /dev/shm
1633081675.458906264: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /
1633081675.458913677: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev
1633081675.458919138: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /dev/shm
1633081675.458924738: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/pts
1633081675.458930585: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/hugepages
1633081675.458935926: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/mqueue
1633081675.458941742: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /proc
1633081675.458947282: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /proc/sys/fs/binfmt_misc
1633081675.458957421: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys
1633081675.458963360: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/kernel/security
1633081675.458971198: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup
1633081675.458978208: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/systemd
1633081675.458984464: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/devices
1633081675.459016603: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/net_cls,net_prio
1633081675.459023104: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/pids
1633081675.459028982: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/cpu,cpuacct
1633081675.459034843: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/blkio
1633081675.459040448: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/perf_event
1633081675.459046085: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/freezer
1633081675.459052685: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/memory
1633081675.459058248: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/hugetlb
1633081675.459063992: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/cpuset
1633081675.459069600: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/pstore
1633081675.459075341: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/kernel/debug
1633081675.459082302: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /run
1633081675.459087893: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /run/user/1000
1633081675.459094325: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /var/lib/nfs/rpc_pipefs
1633081675.459106189: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption
1633081675.459112700: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption
1633081675.459117794: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /tmp
1633081675.459122653: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /dev/shm
1633081675.459147556: src/main/tools/linux-sandbox-pid1.cc:363: calling fork...
1633081675.459245937: src/main/tools/linux-sandbox-pid1.cc:393: child started with PID 2
In file included from /home/ec2-user/opt/gcc-9.1.0/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/../../../../include/c++/9.1.0/x86_64-unknown-linux-gnu/bits/os_defines.h:39,
                 from /home/ec2-user/opt/gcc-9.1.0/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/../../../../include/c++/9.1.0/x86_64-unknown-linux-gnu/bits/c++config.h:524,
                 from /home/ec2-user/opt/gcc-9.1.0/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/../../../../include/c++/9.1.0/type_traits:38,
                 from /home/ec2-user/opt/gcc-9.1.0/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/../../../../include/c++/9.1.0/unordered_map:38,
                 from bazel-out/k8-opt/bin/transpiler/examples/string_reverse/string_reverse_tfhe.cc:1:
/usr/include/features.h:376:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  376 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
gcc: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
1633081684.261167928: src/main/tools/linux-sandbox-pid1.cc:410: wait returned pid=2, status=0x400
1633081684.261180298: src/main/tools/linux-sandbox-pid1.cc:428: child exited normally with code 4
1633081684.296650797: src/main/tools/linux-sandbox.cc:233: child exited normally with code 4
INFO: Elapsed time: 8640.140s, Critical Path: 127.58s
INFO: 5095 processes: 77 internal, 5018 linux-sandbox.
FAILED: Build did NOT complete successfully

---
(VERBOSE MESSAGE)

cd /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption && \
>   exec env - \
>     BAZEL_CXXOPTS='-std=c++17' \
>     LD_LIBRARY_PATH=/home/ec2-user/opt/gcc-9.1.0/lib:/home/ec2-user/opt/gcc-9.1.0/lib64:/home/ec2-user/opt/gcc-9.1.0/lib:/home/ec2-user/opt/gcc-9.1.0/lib64: \
>     PATH=/home/ec2-user/.cache/bazelisk/downloads/bazelbuild/bazel-4.0.0-linux-x86_64/bin:/home/ec2-user/opt/gcc-9.1.0/bin:/home/ec2-user/opt/gcc-9.1.0/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin \
>     PWD=/proc/self/cwd \
>     PYTHON_BIN_PATH=/usr/bin/python3 \
>     TMPDIR=/tmp \
>   /home/ec2-user/.cache/bazel/_bazel_ec2-user/install/1a4a2fac02d50c77031d44c0d91b8920/linux-sandbox -t 15 -w /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption -w /tmp -w /dev/shm -D -- /home/ec2-user/opt/gcc-9.1.0/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++17' -MD -MF bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.d '-frandom-seed=bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -isystem bazel-out/k8-opt/bin/external/tfhe/libtfhe/include -Wno-sign-compare -Wno-comment '-std=c++17' -O0 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/k8-opt/bin/transpiler/examples/string_reverse/string_reverse_tfhe.cc -o bazel-out/k8-opt/bin/transpiler/examples/string_reverse/_objs/string_reverse_tfhe/string_reverse_tfhe.pic.o
1633081928.551917951: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1633081928.551946932: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1633081928.552163678: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 13130
1633081928.552235003: src/main/tools/linux-sandbox-pid1.cc:434: Pid1Main started
1633081928.552476950: src/main/tools/linux-sandbox-pid1.cc:176: working dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption
1633081928.552513906: src/main/tools/linux-sandbox-pid1.cc:208: writable: /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption
1633081928.552526605: src/main/tools/linux-sandbox-pid1.cc:208: writable: /tmp
1633081928.552542624: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1633081928.552597246: src/main/tools/linux-sandbox-pid1.cc:208: writable: /dev/shm
1633081928.552705381: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /
1633081928.552719983: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev
1633081928.552727943: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /dev/shm
1633081928.552735604: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/pts
1633081928.552746655: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/hugepages
1633081928.552752344: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/mqueue
1633081928.552758295: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /proc
1633081928.552765481: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /proc/sys/fs/binfmt_misc
1633081928.552779817: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys
1633081928.552787776: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/kernel/security
1633081928.552797806: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup
1633081928.552810420: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/systemd
1633081928.552826994: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/devices
1633081928.552863628: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/net_cls,net_prio
1633081928.552879945: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/pids
1633081928.552888437: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/cpu,cpuacct
1633081928.552896837: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/blkio
1633081928.552903057: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/perf_event
1633081928.552911217: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/freezer
1633081928.552923014: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/memory
1633081928.552930637: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/hugetlb
1633081928.552936839: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/cpuset
1633081928.552944826: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/pstore
1633081928.552952452: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/kernel/debug
1633081928.552961061: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /run
1633081928.552968571: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /run/user/1000
1633081928.552976498: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /var/lib/nfs/rpc_pipefs
1633081928.552991629: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption
1633081928.553001690: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /home/ec2-user/.cache/bazel/_bazel_ec2-user/f9cbf21ed6e3a79982ef4879961c490e/sandbox/linux-sandbox/5050/execroot/com_google_fully_homomorphic_encryption
1633081928.553009078: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /tmp
1633081928.553014255: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /dev/shm
1633081928.553035610: src/main/tools/linux-sandbox-pid1.cc:363: calling fork...
1633081928.553148980: src/main/tools/linux-sandbox-pid1.cc:393: child started with PID 2
In file included from /home/ec2-user/opt/gcc-9.1.0/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/../../../../include/c++/9.1.0/x86_64-unknown-linux-gnu/bits/os_defines.h:39,
                 from /home/ec2-user/opt/gcc-9.1.0/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/../../../../include/c++/9.1.0/x86_64-unknown-linux-gnu/bits/c++config.h:524,
                 from /home/ec2-user/opt/gcc-9.1.0/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/../../../../include/c++/9.1.0/type_traits:38,
                 from /home/ec2-user/opt/gcc-9.1.0/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/../../../../include/c++/9.1.0/unordered_map:38,
                 from bazel-out/k8-opt/bin/transpiler/examples/string_reverse/string_reverse_tfhe.cc:1:
/usr/include/features.h:376:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  376 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
gcc: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
1633081937.316780606: src/main/tools/linux-sandbox-pid1.cc:410: wait returned pid=2, status=0x400
1633081937.316798991: src/main/tools/linux-sandbox-pid1.cc:428: child exited normally with code 4
1633081937.348607750: src/main/tools/linux-sandbox.cc:233: child exited normally with code 4

**Comment by j2kun** [comment]
The issue is quite old now. Have you tried running this recently? If so, could you post the exact command that you ran? Was it `bazel run //transpiler/examples/string_reverse:string_reverse_tfhe_testbench` ?
