### ISSUE TITLE
Representation Encrypted Number

### ISSUE THREAD

**Issue by subzero210** [google/fully-homomorphic-encryption#19]
Good Morning,
I want to create a script in which the input are the Encrypted number and not the plaintext. I want to realize a simple sum. How can represent the Encrypted Number through int type? Is possible to encode o to serialize the ciphertext in order to give it like input?
Thank you very much!

**Comment by j2kun** [comment]
@subzero210 Have a look at the examples in https://github.com/google/fully-homomorphic-encryption/tree/main/transpiler/examples/simple_sum, which does an encrypted sum of two integers
