### ISSUE TITLE
Issue Building With Bazel

### ISSUE THREAD

**Issue by ArmaghanAsghar** [google/fully-homomorphic-encryption#20]
1. Fully Homomorphic Library with Bazel in Container Environment.
2. Created a new example in Fully Homomorphic Library using openfhe  https://github.com/openfheorg/ library. 
3. The example I am trying to run is https://github.com/openfheorg/openfhe-development/blob/main/src/pke/examples/simple-integers-serial-bgvrns.cpp
4. The example runs fine when I compile and execute openfhe as a standalone project (independent of Fully Homomorphic Library).
5. When I try to run the same example using bazel as part of Fully Homomorphic Library, I get a compilation error, show below
<img width="1428" alt="Screenshot 2022-04-13 at 3 00 53 PM" src="https://user-images.githubusercontent.com/54956731/163277544-e2328793-b2a5-4e28-aac0-232b58b8277e.png">

My steps:
A. I had cloned the repo
B. Created a new folder in examples to host my example code and made a new BUILD file
C. The build file is 
<img width="363" alt="Screenshot 2022-04-13 at 3 03 37 PM" src="https://user-images.githubusercontent.com/54956731/163277844-1c364f0f-1de7-4ac9-88a0-b4dc8e01a461.png">
 
Everything else in the project is constant, and not been altered. 
Trying to understand why the openfhe example is not working within the Fully Homomorphic encryption Library.

**Comment by j2kun** [comment]
I would recommend re-running with `--sandbox_debug` and `--verbose_failures` to get more information about the source of the issue.

Also, please try running an existing openfhe example first to confirm the build issue is not specific to your example.

**Comment by j2kun** [comment]
The dependent library (OpenFHE) has been updated a lot since this issue was first filed, and I've been taking some time to clean up external usability issues. I would recommend trying the build again, and in the mean time I will close this issue and you can reopen if you see further issues.
