### ISSUE TITLE
Using OpenFHE compile error，but Using TFHE is ok

### ISSUE THREAD

**Issue by maltoseeee** [google/fully-homomorphic-encryption#21]
bazel run //transpiler/examples/fibonacci:fibonacci_openfhe_testbench
Starting local Bazel server and connecting to it...
INFO: Analyzed target //transpiler/examples/fibonacci:fibonacci_openfhe_testbench (99 packages loaded, 21005 targets configured).
INFO: Found 1 target...
ERROR: /home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/external/openfhe/BUILD.bazel:55:6: Foreign Cc - CMake: Building binfhe failed: (Exit 1): bash failed: error executing command /bin/bash -c bazel-out/k8-opt/bin/external/openfhe/binfhe_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c bazel-out/k8-opt/bin/external/openfhe/binfhe_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library binfhe

Environment:______________
BUILD_SCRIPT=bazel-out/k8-opt/bin/external/openfhe/binfhe_foreign_cc/build_script.sh
EXT_BUILD_ROOT=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption
BUILD_LOG=bazel-out/k8-opt/bin/external/openfhe/binfhe_foreign_cc/CMake.log
PWD=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/openfhe/binfhe_foreign_cc/wrapper_build_script.sh
PYTHON_BIN_PATH=/usr/bin/python3
TMPDIR=/tmp
EXT_BUILD_DEPS=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/bazel-out/k8-opt/bin/external/openfhe/binfhe.ext_build_deps
BUILD_TMPDIR=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/bazel-out/k8-opt/bin/external/openfhe/binfhe.build_tmpdir
SHLVL=2
BAZEL_CXXOPTS=-std=c++17
CMAKE_BUILD_PARALLEL_LEVEL=16
INSTALLDIR=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/bazel-out/k8-opt/bin/external/openfhe/binfhe
PATH=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption:/home/constexpr/.cache/bazelisk/downloads/bazelbuild/bazel-4.0.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
_=/usr/bin/env
__________________________
+ /home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/external/cmake-3.22.1-linux-x86_64/bin/cmake -DBUILD_BENCHMARKS=OFF -DBUILD_UNITTESTS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=crosstool_bazel.cmake -DCMAKE_INSTALL_PREFIX=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/bazel-out/k8-opt/bin/external/openfhe/binfhe -DCMAKE_PREFIX_PATH=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/bazel-out/k8-opt/bin/external/openfhe/binfhe.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make/bin/make -G 'Unix Makefiles' /home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/external/openfhe
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/gcc - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building in Release mode
-- BUILD_UNITTESTS:  OFF
-- BUILD_EXAMPLES:   ON
-- BUILD_BENCHMARKS: OFF
-- BUILD_EXTRAS:     OFF
-- BUILD_DOCS:       OFF
-- BUILD_STATIC:     OFF
-- BUILD_SHARED:     ON
-- GIT_SUBMOD_AUTO:  ON
-- WITH_BE2:         ON
-- WITH_BE4:         ON
-- WITH_NTL:         OFF
-- WITH_TCM:         OFF
-- WITH_INTEL_HEXL:  OFF
-- WITH_OPENMP:      ON
-- NATIVE_SIZE:      64
-- CKKS_M_FACTOR:    1
-- WITH_NATIVEOPT:   OFF
-- WITH_COVTEST:     OFF
-- BUILTIN_INFO_AVAILABLE is defined
***** INSTALL IS AT /home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/bazel-out/k8-opt/bin/external/openfhe/binfhe; to change, run cmake with -DCMAKE_INSTALL_PREFIX=/your/path
-- Architecture is x86_64
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of __int128
-- Check size of __int128 - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- NATIVEINT is set to 64
-- MATHBACKEND is set to 2
CMake Error at CMakeLists.txt:377 (message):
  Autoconf is not installed.

-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Configuring incomplete, errors occurred!
See also "/home/constexpr/.cache/bazel/_bazel_constexpr/57e8517c1009cf8d8f04e6f3fe94bf13/sandbox/linux-sandbox/1/execroot/com_google_fully_homomorphic_encryption/bazel-out/k8-opt/bin/external/openfhe/binfhe.build_tmpdir/CMakeFiles/CMakeOutput.log".
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/openfhe/binfhe_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/openfhe/binfhe_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/openfhe/binfhe_foreign_cc/CMake.log

Target //transpiler/examples/fibonacci:fibonacci_openfhe_testbench failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.715s, Critical Path: 5.56s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by davidbrucecousins** [comment]
you may need to install autoconf in your system.  --Dave Cousins, OpenFHE team.

**Comment by j2kun** [comment]
Agreed, the error message states the problem

> CMake Error at CMakeLists.txt:377 (message):
> Autoconf is not installed.

Please try installing autoconf and reopen this issue if the problem persists https://www.gnu.org/software/autoconf/
