### ISSUE TITLE
Allow for external contributions to the FHE library

### ISSUE THREAD

**Issue by cathieyun** [google/fully-homomorphic-encryption#27]
Currently, external contributions are not supported - potential contributors are advised to file issues in the project. In order to interface better with the open-source community and to increase the rate of development and improvement, we should support external contributions. This would require setting up an infrastructure similar to Tink (https://github.com/google/tink) for pulling external changes into the Google-internal codebase.

**Comment by j2kun** [comment]
Migrating this Issue to an internal ticket. Work is under way and should be tested/reviewed next week.
