### ISSUE TITLE
Docker with jazzy Ubuntu not compiling (FIX)

### ISSUE THREAD

**Issue by nurev-dev** [google/fully-homomorphic-encryption#33]
The Ubuntu Jazzy docker file fails to build. The reason why is that python2.x is not in the new versions of Ubuntu... only python3. This build requires python2 in addition to python3.

Here's a working fix for the docker file (TESTED):

after line 26 add:
  python2 \\

then add this line after the end of the apt-get command (add this before install deps required section):
RUN ln -s /usr/bin/python2 /usr/bin/python

**Comment by j2kun** [comment]
By the way, @nurev-dev if you want to paste in source code without hitting accidental markdown formatting, you can enclose it in "triple backtick" fences

See https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

Example:

```
# Install required packages.
RUN apt-get update && apt-get install -y \
  gcc \
  git \
  libtinfo5 \
  python3 \
  python3-pip \
  python-is-python3 \
  autoconf \
  libreadline-dev \
  flex \
  bison \
  wget
```
