### ISSUE TITLE
Not able to run the docker command successfuly due to an issue with Bazel

### ISSUE THREAD

**Issue by HritikaPK** [google/fully-homomorphic-encryption#35]
After running the "docker build -t google-fhe-transpiler -f docker/debian-bullseye.Dockerfile ." command in step 2, there is a failure in the build of  Bazel,
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/61798852/213913094-e830b45b-5cb0-40d2-bef8-35bdfebe2b7c.png">

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/61798852/213913104-e0935686-af83-44c2-9dbd-26e5dcccf207.png">

Kindly let me know how can I can proceed.

**Comment by dibakch** [comment]
Did you try to manually download the URL for openjdk?  There seems to be an error with the returned number of bytes from Bazel.  Could you try again?

There might also be some firewalling going on.

**Comment by j2kun** [comment]
+1 I would try manually downloading that URL from mirror.bazel.build.

**Comment by HritikaPK** [comment]
Hello,

Actually, I am pretty new to docker and I don't know how to manually download the URL for a docker machine. Do you mean to say I gotta add a command to the dockerfile source file?  Could you guys guide me a little  :").

**Comment by j2kun** [comment]
The hypothesis is that this is unrelated to docker and instead related to your network connection. Try copying the URL for the openjdk binary and passing it to `wget` or `curl -o` to see if you can download the file independently of bazel/docker. Look at the size of the resulting file to see if it matches the `202599005` bytes expected by bazel.
