### ISSUE TITLE
bazel version 4.0.0

### ISSUE THREAD

**Issue by alphanumericnonsense** [google/fully-homomorphic-encryption#39]
Trying to play hangman.  My version of bazel is 6.1.1, whereas the version specified in `fully-homomorphic-encryption/.bazelversion` is 4.0.0.  Can I change this to a current version?  I'm not even sure where to get 4.0.0 ([here I guess](https://github.com/bazelbuild/bazel/releases/tag/4.0.0)).

**Comment by asraa** [comment]
Hey! I'd recommend using Bazelisk, which manages the bazel version for the build depending on the configuration.

https://github.com/bazelbuild/bazelisk

It can handle the upgrade/downgrading!
