### ISSUE TITLE
Install Error: Bazelisk cannot connect to GCS

### ISSUE THREAD

**Issue by Hang-shao** [google/fully-homomorphic-encryption#4]
choose docker to intsall
have this error：
![image](https://user-images.githubusercontent.com/50350694/122227631-a2dc9900-cee9-11eb-9c06-541dfd70f004.png)

**Comment by umerov-javokhir** [comment]
> choose docker to intsall
> have this error：
> ![image](https://user-images.githubusercontent.com/50350694/122227631-a2dc9900-cee9-11eb-9c06-541dfd70f004.png)

Do you have this 
# ...
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get -y install gcc mono-mcs && \
    rm -rf /var/lib/apt/lists/*

**Comment by Hang-shao** [comment]
thank you, I have a try it.发自我的荣耀手机-------- 原始邮件 --------发件人： umerov-javokhir ***@***.***>日期： 2021年6月17日周四 02:18收件人： google/fully-homomorphic-encryption ***@***.***>抄送： Pamhub ***@***.***>, Author ***@***.***>主    题： Re: [google/fully-homomorphic-encryption] install error (#4)



choose docker to intsall

have this error：





Do you have this

...

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && 

apt-get -y install gcc mono-mcs && 

rm -rf /var/lib/apt/lists/*

**Comment by greenjava1** [comment]
same error as all

**Comment by Hang-shao** [comment]
> > choose docker to intsall
> > have this error：
> > ![image](https://user-images.githubusercontent.com/50350694/122227631-a2dc9900-cee9-11eb-9c06-541dfd70f004.png)
> 
> Do you have this
> 
> # ...
> ENV DEBIAN_FRONTEND noninteractive
> RUN apt-get update &&
> apt-get -y install gcc mono-mcs &&
> rm -rf /var/lib/apt/lists/*

Your method doesn't work.

**Comment by dibakch** [comment]
Thanks for reaching out!  This might be related to an [open issue on Bazelisk](https://github.com/bazelbuild/bazelisk/issues/234).  Could you try adding a line with `ENV BAZELISK_BASE_URL="https://github.com/bazelbuild/bazel/releases/download"` in the `Dockerfile` before any `bazelisk` commands are used?

**Comment by Hang-shao** [comment]
> Thanks for reaching out! This might be related to an [open issue on Bazelisk](https://github.com/bazelbuild/bazelisk/issues/234). Could you try adding a line with `ENV BAZELISK_BASE_URL="https://github.com/bazelbuild/bazel/releases/download"` in the `Dockerfile` before any `bazelisk` commands are used?

Thank you, this problem is OK. But it appears a new problem, I am looking for method to solve it.
![image](https://user-images.githubusercontent.com/50350694/122376374-ad08a100-cf96-11eb-8c51-f877aa284d84.png)

**Comment by dibakch** [comment]
Sounds like a temporary failure on your network.  Could you try again?

**Comment by umerov-javokhir** [comment]
For me, installation of this packages with docker container helped
`
RUN apk update && apk add python3-dev \
                        gcc \
                        libc-dev
`

**Comment by Antonio-demo** [comment]
I have a question about the order(bazel run //transpiler/examples/hangman:hangman_client),the result can't display.
![2021-06-20 15-32-47屏幕截图](https://user-images.githubusercontent.com/72426534/122665917-cef36500-d1dc-11eb-873b-5fc02f71f522.png)
Can you help me solve this question?

**Comment by dibakch** [comment]
@Antonio-demo This seems to be unrelated to this issue and more related to #7.  Could you run `gcc --version` and `g++ --version`?

**Comment by dibakch** [comment]
@Hang-shao Did you give it another try to build the container?  Does this workaround solve your problem?

**Comment by martiny98** [comment]
Hello, for env bazelisk_ BASE_ URL=" https://github.com/bazelbuild/bazel/releases/download "Is this added to the front of the dockerfile file? A lot of attempts are still the original problems
![Uploading image.png…]()

**Comment by greenjava1** [comment]
hello,ubuntu20.14 i try env  BAZELISK_BASE_URL="https://github.com/bazelbuild/bazel/releases/download"
but it doesn`t work~
help~

**Comment by dibakch** [comment]
Can you post the error message, @martiny98 @greenjava1?

**Comment by martiny98** [comment]
![微信图片_20210622143824](https://user-images.githubusercontent.com/63997673/122876129-b5caef80-d367-11eb-8826-2add1a21faf9.png)
thank you!

**Comment by dibakch** [comment]
Thanks!  Indeed, looks as if Bazelisk still tries to connect to GCS and fails.  Could you replace your `Dockerfile` with the following and try again?

```
FROM debian:bullseye

# Install required packages.
RUN apt-get update && apt-get install -y \
	gcc \
	git \
	libtinfo5 \
	python \
	python3 \
	python3-pip \
	wget

# Install bazel
RUN wget -O bazel "https://github.com/bazelbuild/bazel/releases/download/4.0.0/bazel-4.0.0-linux-x86_64" \
	&& test "7bee349a626281fc8b8d04a7a0b0358492712377400ab12533aeb39c2eb2b901  bazel" = "$(sha256sum bazel)" \
	&& chmod +x bazel \
	&& mv bazel /bin/bazel

WORKDIR /usr/src/fhe/

COPY . .

# Build all targets.
RUN bazel build ...
```

**Comment by Hang-shao** [comment]
> 谢谢！事实上，看起来 Bazelisk 仍然尝试连接到 GCS 并且失败了。你能用`Dockerfile`下面的替换你的然后再试一次吗？
> 
> ```
> FROM debian:bullseye
> 
> # Install required packages.
> RUN apt-get update && apt-get install -y \
> 	gcc \
> 	git \
> 	libtinfo5 \
> 	python \
> 	python3 \
> 	python3-pip \
> 	wget
> 
> # Install bazel
> RUN wget -O bazel "https://github.com/bazelbuild/bazel/releases/download/4.0.0/bazel-4.0.0-linux-x86_64" \
> 	&& test "7bee349a626281fc8b8d04a7a0b0358492712377400ab12533aeb39c2eb2b901  bazel" = "$(sha256sum bazel)" \
> 	&& chmod +x bazel \
> 	&& mv bazel /bin/bazel
> 
> WORKDIR /usr/src/fhe/
> 
> COPY . .
> 
> # Build all targets.
> RUN bazel build ...
> ```
I've tried, and the following error has occurred：
![image](https://user-images.githubusercontent.com/50350694/122918127-613c6a00-d391-11eb-9327-23c6a46ac46c.png)

**Comment by Hang-shao** [comment]
> @Hang-shao您是否再次尝试构建容器？此解决方法是否解决了您的问题？

After I rebuilt the container, I added: ENV BAZELISK_BASE_URL="https://github.com/bazelbuild/bazel/releases/download"
But there was a mistake. As follows: 
![image](https://user-images.githubusercontent.com/50350694/122918528-cd1ed280-d391-11eb-8f24-9c3d93c8d370.png)

**Comment by dibakch** [comment]
Thanks!

It looks like the workaround with the ENV variable does not work as Bazelisk still tries to connect to the GCS bucket that you cannot connect to.  Looks like the [workaround with installing bazel](#issuecomment-865750510) results in another error where you have only a temporary network issue and it is only a connection to GitHub where your connection timed out.  Could you try this again?
