### ISSUE TITLE
no make?

### ISSUE THREAD

**Issue by 0xtrzy** [google/fully-homomorphic-encryption#5]
I download this
but how creating a library and make a program?

any sugestion? debian on arm

**Comment by maxmcd** [comment]
https://github.com/google/fully-homomorphic-encryption/tree/main/transpiler

**Comment by dibakch** [comment]
Thanks for reaching out!  We are using Bazel instead of Make.  Please take a look at https://github.com/google/fully-homomorphic-encryption/tree/main/transpiler#install-the-fhe-c-transpiler for how to install and run the transpiler.
