### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by MarianoDiMartino** [google/fully-homomorphic-encryption#7]
When I run 'bazel run //transpiler/examples/hangman:hangman_client --sandbox_debug'

I get the following compiler error:

> INFO: Analyzed target //transpiler/examples/hangman:hangman_client (0 packages loaded, 0 targets configured).
> INFO: Found 1 target...
> ERROR: /home/mariano/FHE/fully-homomorphic-encryption/transpiler/struct_transpiler/BUILD:25:10: Linking transpiler/struct_transpiler/struct_transpiler failed: (Exit 1): process-wrapper failed: error executing command 
>   (cd /home/mariano/.cache/bazel/_bazel_mariano/44625b1d8cdb8f2a3f51804e0547c5c1/sandbox/processwrapper-sandbox/48/execroot/com_google_fully_homomorphic_encryption && \
>   exec env - \
>     PATH=/home/mariano/.cache/bazelisk/downloads/bazelbuild/bazel-4.0.0-linux-x86_64/bin: ...
>     PWD=/proc/self/cwd \
>     TMPDIR=/tmp \
>   /home/mariano/.cache/bazel/_bazel_mariano/install/1a4a2fac02d50c77031d44c0d91b8920/process-wrapper '--timeout=0' '--kill_delay=15' /usr/bin/gcc @bazel-out/k8-opt-exec-2B5CBBC6/bin/transpiler/struct_transpiler/struct_transpiler-2.params) process-wrapper failed: error executing command 
>   (cd /home/mariano/.cache/bazel/_bazel_mariano/44625b1d8cdb8f2a3f51804e0547c5c1/sandbox/processwrapper-sandbox/48/execroot/com_google_fully_homomorphic_encryption && \
>   exec env - \
>     PATH=/home/mariano/.cache/bazelisk/downloads/bazelbuild/bazel-4.0.0-linux-x86_64/bin: ...
>     PWD=/proc/self/cwd \
>     TMPDIR=/tmp \
>   /home/mariano/.cache/bazel/_bazel_mariano/install/1a4a2fac02d50c77031d44c0d91b8920/process-wrapper '--timeout=0' '--kill_delay=15' /usr/bin/gcc @bazel-out/k8-opt-exec-2B5CBBC6/bin/transpiler/struct_transpiler/struct_transpiler-2.params)
> bazel-out/k8-opt-exec-2B5CBBC6/bin/transpiler/struct_transpiler/_objs/struct_transpiler/struct_transpiler_main.o:struct_transpiler_main.cc:function fully_homomorphic_encryption::transpiler::RealMain(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >): error: undefined reference to 'std::filesystem::__cxx11::path::_M_split_cmpts()'
> bazel-out/k8-opt-exec-2B5CBBC6/bin/transpiler/struct_transpiler/_objs/struct_transpiler/struct_transpiler_main.o:struct_transpiler_main.cc:function fully_homomorphic_encryption::transpiler::RealMain(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >): error: undefined reference to 'std::filesystem::__cxx11::path::_M_split_cmpts()'
> collect2: error: ld returned 1 exit status
> Target //transpiler/examples/hangman:hangman_client failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 5.662s, Critical Path: 5.23s
> INFO: 27 processes: 5 internal, 22 processwrapper-sandbox.
> FAILED: Build did NOT complete successfully
> FAILED: Build did NOT complete successfully

uname -a
> Linux mariano 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by dibakch** [comment]
What version of gcc are you using?  Can you post the output of `gcc --version` and `g++ --version`?

**Comment by MarianoDiMartino** [comment]
I see Debian 10 doesn't have gcc-9 in stable. I was still compiling with gcc-8, I guess that must be the issue.
Thank you.
