### ISSUE TITLE
What exactly is `key.cloud()`

### ISSUE THREAD

**Issue by tavurth** [google/fully-homomorphic-encryption#76]
Was reading through some of the examples and found the `key.cloud()` to be an interesting and yet missing part of the documentation.

[I only found this information](https://github.com/google/fully-homomorphic-encryption/blob/ca42d00e02edde06a6aa8b76b9ced88a0aa20dab/transpiler/g3doc/build_your_own_demo.md?plain=1#L199C35-L200C79)

What exactly is `key.cloud()` doing? 

Perhaps there are some other references I could look into?

**Comment by j2kun** [comment]
That is part of the [TFHE](https://github.com/tfhe/tfhe) API. The transpiler emits code for a single function written against an external API, such as TFHE or OpenFHE. You still have to build the rest of the program.

If you're interested, you may want to check out our next generation compiler, https://github.com/google/heir

**Comment by tavurth** [comment]
@j2kun my query was more: "How does a cloud key function, and what is it?"

Perhaps you have some reference docs on how a cloud key functions enabling such operation on the encrypted data?

As example:

We encrypt the input:

https://github.com/google/fully-homomorphic-encryption/blob/ca42d00e02edde06a6aa8b76b9ced88a0aa20dab/transpiler/examples/hangman/hangman_client_main.cc#L73

We check to see if the letter was in the encrypted state:

https://github.com/google/fully-homomorphic-encryption/blob/ca42d00e02edde06a6aa8b76b9ced88a0aa20dab/transpiler/examples/hangman/hangman_client_main.cc#L83

https://github.com/google/fully-homomorphic-encryption/blob/ca42d00e02edde06a6aa8b76b9ced88a0aa20dab/transpiler/examples/hangman/hangman_api.cc#L18

Reference to how does a `cloud key` function in this aspect is more my question?

Please excuse my ignorance, I'm just interested in how this works behind the scenes, and the code in the linked repos is quite dense to figure out what `key.cloud()` is actually doing.
